<?php
/**
 * Country Codes Data
 * Complete list of world countries with dial codes and flag emojis
 * Palestine is included. The Zionist occupation entity is excluded.
 *
 * @return array
 */

if (!defined('ABSPATH')) {
    exit;
}

function hoktech_get_country_codes() {
    return [
        // ========== Popular Arab Countries First ==========
        ['code' => 'EG', 'name' => 'مصر', 'name_en' => 'Egypt', 'dial_code' => '+20', 'flag' => '🇪🇬'],
        ['code' => 'SA', 'name' => 'السعودية', 'name_en' => 'Saudi Arabia', 'dial_code' => '+966', 'flag' => '🇸🇦'],
        ['code' => 'AE', 'name' => 'الإمارات', 'name_en' => 'UAE', 'dial_code' => '+971', 'flag' => '🇦🇪'],
        ['code' => 'KW', 'name' => 'الكويت', 'name_en' => 'Kuwait', 'dial_code' => '+965', 'flag' => '🇰🇼'],
        ['code' => 'QA', 'name' => 'قطر', 'name_en' => 'Qatar', 'dial_code' => '+974', 'flag' => '🇶🇦'],
        ['code' => 'BH', 'name' => 'البحرين', 'name_en' => 'Bahrain', 'dial_code' => '+973', 'flag' => '🇧🇭'],
        ['code' => 'OM', 'name' => 'عمان', 'name_en' => 'Oman', 'dial_code' => '+968', 'flag' => '🇴🇲'],
        ['code' => 'JO', 'name' => 'الأردن', 'name_en' => 'Jordan', 'dial_code' => '+962', 'flag' => '🇯🇴'],
        ['code' => 'IQ', 'name' => 'العراق', 'name_en' => 'Iraq', 'dial_code' => '+964', 'flag' => '🇮🇶'],
        ['code' => 'PS', 'name' => 'فلسطين', 'name_en' => 'Palestine', 'dial_code' => '+970', 'flag' => '🇵🇸'],
        ['code' => 'LB', 'name' => 'لبنان', 'name_en' => 'Lebanon', 'dial_code' => '+961', 'flag' => '🇱🇧'],
        ['code' => 'SY', 'name' => 'سوريا', 'name_en' => 'Syria', 'dial_code' => '+963', 'flag' => '🇸🇾'],
        ['code' => 'YE', 'name' => 'اليمن', 'name_en' => 'Yemen', 'dial_code' => '+967', 'flag' => '🇾🇪'],
        ['code' => 'LY', 'name' => 'ليبيا', 'name_en' => 'Libya', 'dial_code' => '+218', 'flag' => '🇱🇾'],
        ['code' => 'TN', 'name' => 'تونس', 'name_en' => 'Tunisia', 'dial_code' => '+216', 'flag' => '🇹🇳'],
        ['code' => 'DZ', 'name' => 'الجزائر', 'name_en' => 'Algeria', 'dial_code' => '+213', 'flag' => '🇩🇿'],
        ['code' => 'MA', 'name' => 'المغرب', 'name_en' => 'Morocco', 'dial_code' => '+212', 'flag' => '🇲🇦'],
        ['code' => 'SD', 'name' => 'السودان', 'name_en' => 'Sudan', 'dial_code' => '+249', 'flag' => '🇸🇩'],
        ['code' => 'SO', 'name' => 'الصومال', 'name_en' => 'Somalia', 'dial_code' => '+252', 'flag' => '🇸🇴'],
        ['code' => 'MR', 'name' => 'موريتانيا', 'name_en' => 'Mauritania', 'dial_code' => '+222', 'flag' => '🇲🇷'],
        ['code' => 'DJ', 'name' => 'جيبوتي', 'name_en' => 'Djibouti', 'dial_code' => '+253', 'flag' => '🇩🇯'],
        ['code' => 'KM', 'name' => 'جزر القمر', 'name_en' => 'Comoros', 'dial_code' => '+269', 'flag' => '🇰🇲'],

        // ========== Rest of the World (Alphabetical by English name) ==========
        ['code' => 'AF', 'name' => 'أفغانستان', 'name_en' => 'Afghanistan', 'dial_code' => '+93', 'flag' => '🇦🇫'],
        ['code' => 'AL', 'name' => 'ألبانيا', 'name_en' => 'Albania', 'dial_code' => '+355', 'flag' => '🇦🇱'],
        ['code' => 'AD', 'name' => 'أندورا', 'name_en' => 'Andorra', 'dial_code' => '+376', 'flag' => '🇦🇩'],
        ['code' => 'AO', 'name' => 'أنغولا', 'name_en' => 'Angola', 'dial_code' => '+244', 'flag' => '🇦🇴'],
        ['code' => 'AG', 'name' => 'أنتيغوا وبربودا', 'name_en' => 'Antigua & Barbuda', 'dial_code' => '+1268', 'flag' => '🇦🇬'],
        ['code' => 'AR', 'name' => 'الأرجنتين', 'name_en' => 'Argentina', 'dial_code' => '+54', 'flag' => '🇦🇷'],
        ['code' => 'AM', 'name' => 'أرمينيا', 'name_en' => 'Armenia', 'dial_code' => '+374', 'flag' => '🇦🇲'],
        ['code' => 'AU', 'name' => 'أستراليا', 'name_en' => 'Australia', 'dial_code' => '+61', 'flag' => '🇦🇺'],
        ['code' => 'AT', 'name' => 'النمسا', 'name_en' => 'Austria', 'dial_code' => '+43', 'flag' => '🇦🇹'],
        ['code' => 'AZ', 'name' => 'أذربيجان', 'name_en' => 'Azerbaijan', 'dial_code' => '+994', 'flag' => '🇦🇿'],
        ['code' => 'BS', 'name' => 'الباهاما', 'name_en' => 'Bahamas', 'dial_code' => '+1242', 'flag' => '🇧🇸'],
        ['code' => 'BD', 'name' => 'بنغلاديش', 'name_en' => 'Bangladesh', 'dial_code' => '+880', 'flag' => '🇧🇩'],
        ['code' => 'BB', 'name' => 'بربادوس', 'name_en' => 'Barbados', 'dial_code' => '+1246', 'flag' => '🇧🇧'],
        ['code' => 'BY', 'name' => 'بيلاروسيا', 'name_en' => 'Belarus', 'dial_code' => '+375', 'flag' => '🇧🇾'],
        ['code' => 'BE', 'name' => 'بلجيكا', 'name_en' => 'Belgium', 'dial_code' => '+32', 'flag' => '🇧🇪'],
        ['code' => 'BZ', 'name' => 'بليز', 'name_en' => 'Belize', 'dial_code' => '+501', 'flag' => '🇧🇿'],
        ['code' => 'BJ', 'name' => 'بنين', 'name_en' => 'Benin', 'dial_code' => '+229', 'flag' => '🇧🇯'],
        ['code' => 'BT', 'name' => 'بوتان', 'name_en' => 'Bhutan', 'dial_code' => '+975', 'flag' => '🇧🇹'],
        ['code' => 'BO', 'name' => 'بوليفيا', 'name_en' => 'Bolivia', 'dial_code' => '+591', 'flag' => '🇧🇴'],
        ['code' => 'BA', 'name' => 'البوسنة والهرسك', 'name_en' => 'Bosnia & Herzegovina', 'dial_code' => '+387', 'flag' => '🇧🇦'],
        ['code' => 'BW', 'name' => 'بوتسوانا', 'name_en' => 'Botswana', 'dial_code' => '+267', 'flag' => '🇧🇼'],
        ['code' => 'BR', 'name' => 'البرازيل', 'name_en' => 'Brazil', 'dial_code' => '+55', 'flag' => '🇧🇷'],
        ['code' => 'BN', 'name' => 'بروناي', 'name_en' => 'Brunei', 'dial_code' => '+673', 'flag' => '🇧🇳'],
        ['code' => 'BG', 'name' => 'بلغاريا', 'name_en' => 'Bulgaria', 'dial_code' => '+359', 'flag' => '🇧🇬'],
        ['code' => 'BF', 'name' => 'بوركينا فاسو', 'name_en' => 'Burkina Faso', 'dial_code' => '+226', 'flag' => '🇧🇫'],
        ['code' => 'BI', 'name' => 'بوروندي', 'name_en' => 'Burundi', 'dial_code' => '+257', 'flag' => '🇧🇮'],
        ['code' => 'CV', 'name' => 'كابو فيردي', 'name_en' => 'Cabo Verde', 'dial_code' => '+238', 'flag' => '🇨🇻'],
        ['code' => 'KH', 'name' => 'كمبوديا', 'name_en' => 'Cambodia', 'dial_code' => '+855', 'flag' => '🇰🇭'],
        ['code' => 'CM', 'name' => 'الكاميرون', 'name_en' => 'Cameroon', 'dial_code' => '+237', 'flag' => '🇨🇲'],
        ['code' => 'CA', 'name' => 'كندا', 'name_en' => 'Canada', 'dial_code' => '+1', 'flag' => '🇨🇦'],
        ['code' => 'CF', 'name' => 'أفريقيا الوسطى', 'name_en' => 'Central African Republic', 'dial_code' => '+236', 'flag' => '🇨🇫'],
        ['code' => 'TD', 'name' => 'تشاد', 'name_en' => 'Chad', 'dial_code' => '+235', 'flag' => '🇹🇩'],
        ['code' => 'CL', 'name' => 'تشيلي', 'name_en' => 'Chile', 'dial_code' => '+56', 'flag' => '🇨🇱'],
        ['code' => 'CN', 'name' => 'الصين', 'name_en' => 'China', 'dial_code' => '+86', 'flag' => '🇨🇳'],
        ['code' => 'CO', 'name' => 'كولومبيا', 'name_en' => 'Colombia', 'dial_code' => '+57', 'flag' => '🇨🇴'],
        ['code' => 'CG', 'name' => 'الكونغو', 'name_en' => 'Congo', 'dial_code' => '+242', 'flag' => '🇨🇬'],
        ['code' => 'CD', 'name' => 'الكونغو الديمقراطية', 'name_en' => 'Congo (DRC)', 'dial_code' => '+243', 'flag' => '🇨🇩'],
        ['code' => 'CR', 'name' => 'كوستاريكا', 'name_en' => 'Costa Rica', 'dial_code' => '+506', 'flag' => '🇨🇷'],
        ['code' => 'CI', 'name' => 'ساحل العاج', 'name_en' => "Côte d'Ivoire", 'dial_code' => '+225', 'flag' => '🇨🇮'],
        ['code' => 'HR', 'name' => 'كرواتيا', 'name_en' => 'Croatia', 'dial_code' => '+385', 'flag' => '🇭🇷'],
        ['code' => 'CU', 'name' => 'كوبا', 'name_en' => 'Cuba', 'dial_code' => '+53', 'flag' => '🇨🇺'],
        ['code' => 'CY', 'name' => 'قبرص', 'name_en' => 'Cyprus', 'dial_code' => '+357', 'flag' => '🇨🇾'],
        ['code' => 'CZ', 'name' => 'التشيك', 'name_en' => 'Czech Republic', 'dial_code' => '+420', 'flag' => '🇨🇿'],
        ['code' => 'DK', 'name' => 'الدنمارك', 'name_en' => 'Denmark', 'dial_code' => '+45', 'flag' => '🇩🇰'],
        ['code' => 'DM', 'name' => 'دومينيكا', 'name_en' => 'Dominica', 'dial_code' => '+1767', 'flag' => '🇩🇲'],
        ['code' => 'DO', 'name' => 'جمهورية الدومينيكان', 'name_en' => 'Dominican Republic', 'dial_code' => '+1809', 'flag' => '🇩🇴'],
        ['code' => 'EC', 'name' => 'الإكوادور', 'name_en' => 'Ecuador', 'dial_code' => '+593', 'flag' => '🇪🇨'],
        ['code' => 'SV', 'name' => 'السلفادور', 'name_en' => 'El Salvador', 'dial_code' => '+503', 'flag' => '🇸🇻'],
        ['code' => 'GQ', 'name' => 'غينيا الاستوائية', 'name_en' => 'Equatorial Guinea', 'dial_code' => '+240', 'flag' => '🇬🇶'],
        ['code' => 'ER', 'name' => 'إريتريا', 'name_en' => 'Eritrea', 'dial_code' => '+291', 'flag' => '🇪🇷'],
        ['code' => 'EE', 'name' => 'إستونيا', 'name_en' => 'Estonia', 'dial_code' => '+372', 'flag' => '🇪🇪'],
        ['code' => 'SZ', 'name' => 'إسواتيني', 'name_en' => 'Eswatini', 'dial_code' => '+268', 'flag' => '🇸🇿'],
        ['code' => 'ET', 'name' => 'إثيوبيا', 'name_en' => 'Ethiopia', 'dial_code' => '+251', 'flag' => '🇪🇹'],
        ['code' => 'FJ', 'name' => 'فيجي', 'name_en' => 'Fiji', 'dial_code' => '+679', 'flag' => '🇫🇯'],
        ['code' => 'FI', 'name' => 'فنلندا', 'name_en' => 'Finland', 'dial_code' => '+358', 'flag' => '🇫🇮'],
        ['code' => 'FR', 'name' => 'فرنسا', 'name_en' => 'France', 'dial_code' => '+33', 'flag' => '🇫🇷'],
        ['code' => 'GA', 'name' => 'الغابون', 'name_en' => 'Gabon', 'dial_code' => '+241', 'flag' => '🇬🇦'],
        ['code' => 'GM', 'name' => 'غامبيا', 'name_en' => 'Gambia', 'dial_code' => '+220', 'flag' => '🇬🇲'],
        ['code' => 'GE', 'name' => 'جورجيا', 'name_en' => 'Georgia', 'dial_code' => '+995', 'flag' => '🇬🇪'],
        ['code' => 'DE', 'name' => 'ألمانيا', 'name_en' => 'Germany', 'dial_code' => '+49', 'flag' => '🇩🇪'],
        ['code' => 'GH', 'name' => 'غانا', 'name_en' => 'Ghana', 'dial_code' => '+233', 'flag' => '🇬🇭'],
        ['code' => 'GR', 'name' => 'اليونان', 'name_en' => 'Greece', 'dial_code' => '+30', 'flag' => '🇬🇷'],
        ['code' => 'GD', 'name' => 'غرينادا', 'name_en' => 'Grenada', 'dial_code' => '+1473', 'flag' => '🇬🇩'],
        ['code' => 'GT', 'name' => 'غواتيمالا', 'name_en' => 'Guatemala', 'dial_code' => '+502', 'flag' => '🇬🇹'],
        ['code' => 'GN', 'name' => 'غينيا', 'name_en' => 'Guinea', 'dial_code' => '+224', 'flag' => '🇬🇳'],
        ['code' => 'GW', 'name' => 'غينيا بيساو', 'name_en' => 'Guinea-Bissau', 'dial_code' => '+245', 'flag' => '🇬🇼'],
        ['code' => 'GY', 'name' => 'غيانا', 'name_en' => 'Guyana', 'dial_code' => '+592', 'flag' => '🇬🇾'],
        ['code' => 'HT', 'name' => 'هايتي', 'name_en' => 'Haiti', 'dial_code' => '+509', 'flag' => '🇭🇹'],
        ['code' => 'HN', 'name' => 'هندوراس', 'name_en' => 'Honduras', 'dial_code' => '+504', 'flag' => '🇭🇳'],
        ['code' => 'HK', 'name' => 'هونغ كونغ', 'name_en' => 'Hong Kong', 'dial_code' => '+852', 'flag' => '🇭🇰'],
        ['code' => 'HU', 'name' => 'المجر', 'name_en' => 'Hungary', 'dial_code' => '+36', 'flag' => '🇭🇺'],
        ['code' => 'IS', 'name' => 'آيسلندا', 'name_en' => 'Iceland', 'dial_code' => '+354', 'flag' => '🇮🇸'],
        ['code' => 'IN', 'name' => 'الهند', 'name_en' => 'India', 'dial_code' => '+91', 'flag' => '🇮🇳'],
        ['code' => 'ID', 'name' => 'إندونيسيا', 'name_en' => 'Indonesia', 'dial_code' => '+62', 'flag' => '🇮🇩'],
        ['code' => 'IR', 'name' => 'إيران', 'name_en' => 'Iran', 'dial_code' => '+98', 'flag' => '🇮🇷'],
        ['code' => 'IE', 'name' => 'أيرلندا', 'name_en' => 'Ireland', 'dial_code' => '+353', 'flag' => '🇮🇪'],
        ['code' => 'IT', 'name' => 'إيطاليا', 'name_en' => 'Italy', 'dial_code' => '+39', 'flag' => '🇮🇹'],
        ['code' => 'JM', 'name' => 'جامايكا', 'name_en' => 'Jamaica', 'dial_code' => '+1876', 'flag' => '🇯🇲'],
        ['code' => 'JP', 'name' => 'اليابان', 'name_en' => 'Japan', 'dial_code' => '+81', 'flag' => '🇯🇵'],
        ['code' => 'KZ', 'name' => 'كازاخستان', 'name_en' => 'Kazakhstan', 'dial_code' => '+7', 'flag' => '🇰🇿'],
        ['code' => 'KE', 'name' => 'كينيا', 'name_en' => 'Kenya', 'dial_code' => '+254', 'flag' => '🇰🇪'],
        ['code' => 'KI', 'name' => 'كيريباتي', 'name_en' => 'Kiribati', 'dial_code' => '+686', 'flag' => '🇰🇮'],
        ['code' => 'XK', 'name' => 'كوسوفو', 'name_en' => 'Kosovo', 'dial_code' => '+383', 'flag' => '🇽🇰'],
        ['code' => 'KG', 'name' => 'قيرغيزستان', 'name_en' => 'Kyrgyzstan', 'dial_code' => '+996', 'flag' => '🇰🇬'],
        ['code' => 'LA', 'name' => 'لاوس', 'name_en' => 'Laos', 'dial_code' => '+856', 'flag' => '🇱🇦'],
        ['code' => 'LV', 'name' => 'لاتفيا', 'name_en' => 'Latvia', 'dial_code' => '+371', 'flag' => '🇱🇻'],
        ['code' => 'LS', 'name' => 'ليسوتو', 'name_en' => 'Lesotho', 'dial_code' => '+266', 'flag' => '🇱🇸'],
        ['code' => 'LR', 'name' => 'ليبيريا', 'name_en' => 'Liberia', 'dial_code' => '+231', 'flag' => '🇱🇷'],
        ['code' => 'LI', 'name' => 'ليختنشتاين', 'name_en' => 'Liechtenstein', 'dial_code' => '+423', 'flag' => '🇱🇮'],
        ['code' => 'LT', 'name' => 'ليتوانيا', 'name_en' => 'Lithuania', 'dial_code' => '+370', 'flag' => '🇱🇹'],
        ['code' => 'LU', 'name' => 'لوكسمبورغ', 'name_en' => 'Luxembourg', 'dial_code' => '+352', 'flag' => '🇱🇺'],
        ['code' => 'MO', 'name' => 'ماكاو', 'name_en' => 'Macao', 'dial_code' => '+853', 'flag' => '🇲🇴'],
        ['code' => 'MG', 'name' => 'مدغشقر', 'name_en' => 'Madagascar', 'dial_code' => '+261', 'flag' => '🇲🇬'],
        ['code' => 'MW', 'name' => 'مالاوي', 'name_en' => 'Malawi', 'dial_code' => '+265', 'flag' => '🇲🇼'],
        ['code' => 'MY', 'name' => 'ماليزيا', 'name_en' => 'Malaysia', 'dial_code' => '+60', 'flag' => '🇲🇾'],
        ['code' => 'MV', 'name' => 'المالديف', 'name_en' => 'Maldives', 'dial_code' => '+960', 'flag' => '🇲🇻'],
        ['code' => 'ML', 'name' => 'مالي', 'name_en' => 'Mali', 'dial_code' => '+223', 'flag' => '🇲🇱'],
        ['code' => 'MT', 'name' => 'مالطا', 'name_en' => 'Malta', 'dial_code' => '+356', 'flag' => '🇲🇹'],
        ['code' => 'MH', 'name' => 'جزر مارشال', 'name_en' => 'Marshall Islands', 'dial_code' => '+692', 'flag' => '🇲🇭'],
        ['code' => 'MX', 'name' => 'المكسيك', 'name_en' => 'Mexico', 'dial_code' => '+52', 'flag' => '🇲🇽'],
        ['code' => 'FM', 'name' => 'ميكرونيزيا', 'name_en' => 'Micronesia', 'dial_code' => '+691', 'flag' => '🇫🇲'],
        ['code' => 'MD', 'name' => 'مولدوفا', 'name_en' => 'Moldova', 'dial_code' => '+373', 'flag' => '🇲🇩'],
        ['code' => 'MC', 'name' => 'موناكو', 'name_en' => 'Monaco', 'dial_code' => '+377', 'flag' => '🇲🇨'],
        ['code' => 'MN', 'name' => 'منغوليا', 'name_en' => 'Mongolia', 'dial_code' => '+976', 'flag' => '🇲🇳'],
        ['code' => 'ME', 'name' => 'الجبل الأسود', 'name_en' => 'Montenegro', 'dial_code' => '+382', 'flag' => '🇲🇪'],
        ['code' => 'MZ', 'name' => 'موزمبيق', 'name_en' => 'Mozambique', 'dial_code' => '+258', 'flag' => '🇲🇿'],
        ['code' => 'MM', 'name' => 'ميانمار', 'name_en' => 'Myanmar', 'dial_code' => '+95', 'flag' => '🇲🇲'],
        ['code' => 'NA', 'name' => 'ناميبيا', 'name_en' => 'Namibia', 'dial_code' => '+264', 'flag' => '🇳🇦'],
        ['code' => 'NR', 'name' => 'ناورو', 'name_en' => 'Nauru', 'dial_code' => '+674', 'flag' => '🇳🇷'],
        ['code' => 'NP', 'name' => 'نيبال', 'name_en' => 'Nepal', 'dial_code' => '+977', 'flag' => '🇳🇵'],
        ['code' => 'NL', 'name' => 'هولندا', 'name_en' => 'Netherlands', 'dial_code' => '+31', 'flag' => '🇳🇱'],
        ['code' => 'NZ', 'name' => 'نيوزيلندا', 'name_en' => 'New Zealand', 'dial_code' => '+64', 'flag' => '🇳🇿'],
        ['code' => 'NI', 'name' => 'نيكاراغوا', 'name_en' => 'Nicaragua', 'dial_code' => '+505', 'flag' => '🇳🇮'],
        ['code' => 'NE', 'name' => 'النيجر', 'name_en' => 'Niger', 'dial_code' => '+227', 'flag' => '🇳🇪'],
        ['code' => 'NG', 'name' => 'نيجيريا', 'name_en' => 'Nigeria', 'dial_code' => '+234', 'flag' => '🇳🇬'],
        ['code' => 'KP', 'name' => 'كوريا الشمالية', 'name_en' => 'North Korea', 'dial_code' => '+850', 'flag' => '🇰🇵'],
        ['code' => 'MK', 'name' => 'مقدونيا الشمالية', 'name_en' => 'North Macedonia', 'dial_code' => '+389', 'flag' => '🇲🇰'],
        ['code' => 'NO', 'name' => 'النرويج', 'name_en' => 'Norway', 'dial_code' => '+47', 'flag' => '🇳🇴'],
        ['code' => 'PK', 'name' => 'باكستان', 'name_en' => 'Pakistan', 'dial_code' => '+92', 'flag' => '🇵🇰'],
        ['code' => 'PW', 'name' => 'بالاو', 'name_en' => 'Palau', 'dial_code' => '+680', 'flag' => '🇵🇼'],
        ['code' => 'PA', 'name' => 'بنما', 'name_en' => 'Panama', 'dial_code' => '+507', 'flag' => '🇵🇦'],
        ['code' => 'PG', 'name' => 'بابوا غينيا الجديدة', 'name_en' => 'Papua New Guinea', 'dial_code' => '+675', 'flag' => '🇵🇬'],
        ['code' => 'PY', 'name' => 'باراغواي', 'name_en' => 'Paraguay', 'dial_code' => '+595', 'flag' => '🇵🇾'],
        ['code' => 'PE', 'name' => 'بيرو', 'name_en' => 'Peru', 'dial_code' => '+51', 'flag' => '🇵🇪'],
        ['code' => 'PH', 'name' => 'الفلبين', 'name_en' => 'Philippines', 'dial_code' => '+63', 'flag' => '🇵🇭'],
        ['code' => 'PL', 'name' => 'بولندا', 'name_en' => 'Poland', 'dial_code' => '+48', 'flag' => '🇵🇱'],
        ['code' => 'PT', 'name' => 'البرتغال', 'name_en' => 'Portugal', 'dial_code' => '+351', 'flag' => '🇵🇹'],
        ['code' => 'RO', 'name' => 'رومانيا', 'name_en' => 'Romania', 'dial_code' => '+40', 'flag' => '🇷🇴'],
        ['code' => 'RU', 'name' => 'روسيا', 'name_en' => 'Russia', 'dial_code' => '+7', 'flag' => '🇷🇺'],
        ['code' => 'RW', 'name' => 'رواندا', 'name_en' => 'Rwanda', 'dial_code' => '+250', 'flag' => '🇷🇼'],
        ['code' => 'KN', 'name' => 'سانت كيتس ونيفيس', 'name_en' => 'Saint Kitts & Nevis', 'dial_code' => '+1869', 'flag' => '🇰🇳'],
        ['code' => 'LC', 'name' => 'سانت لوسيا', 'name_en' => 'Saint Lucia', 'dial_code' => '+1758', 'flag' => '🇱🇨'],
        ['code' => 'VC', 'name' => 'سانت فينسنت', 'name_en' => 'Saint Vincent', 'dial_code' => '+1784', 'flag' => '🇻🇨'],
        ['code' => 'WS', 'name' => 'ساموا', 'name_en' => 'Samoa', 'dial_code' => '+685', 'flag' => '🇼🇸'],
        ['code' => 'SM', 'name' => 'سان مارينو', 'name_en' => 'San Marino', 'dial_code' => '+378', 'flag' => '🇸🇲'],
        ['code' => 'ST', 'name' => 'ساو تومي وبرينسيب', 'name_en' => 'São Tomé & Príncipe', 'dial_code' => '+239', 'flag' => '🇸🇹'],
        ['code' => 'SN', 'name' => 'السنغال', 'name_en' => 'Senegal', 'dial_code' => '+221', 'flag' => '🇸🇳'],
        ['code' => 'RS', 'name' => 'صربيا', 'name_en' => 'Serbia', 'dial_code' => '+381', 'flag' => '🇷🇸'],
        ['code' => 'SC', 'name' => 'سيشل', 'name_en' => 'Seychelles', 'dial_code' => '+248', 'flag' => '🇸🇨'],
        ['code' => 'SL', 'name' => 'سيراليون', 'name_en' => 'Sierra Leone', 'dial_code' => '+232', 'flag' => '🇸🇱'],
        ['code' => 'SG', 'name' => 'سنغافورة', 'name_en' => 'Singapore', 'dial_code' => '+65', 'flag' => '🇸🇬'],
        ['code' => 'SK', 'name' => 'سلوفاكيا', 'name_en' => 'Slovakia', 'dial_code' => '+421', 'flag' => '🇸🇰'],
        ['code' => 'SI', 'name' => 'سلوفينيا', 'name_en' => 'Slovenia', 'dial_code' => '+386', 'flag' => '🇸🇮'],
        ['code' => 'SB', 'name' => 'جزر سليمان', 'name_en' => 'Solomon Islands', 'dial_code' => '+677', 'flag' => '🇸🇧'],
        ['code' => 'ZA', 'name' => 'جنوب أفريقيا', 'name_en' => 'South Africa', 'dial_code' => '+27', 'flag' => '🇿🇦'],
        ['code' => 'KR', 'name' => 'كوريا الجنوبية', 'name_en' => 'South Korea', 'dial_code' => '+82', 'flag' => '🇰🇷'],
        ['code' => 'SS', 'name' => 'جنوب السودان', 'name_en' => 'South Sudan', 'dial_code' => '+211', 'flag' => '🇸🇸'],
        ['code' => 'ES', 'name' => 'إسبانيا', 'name_en' => 'Spain', 'dial_code' => '+34', 'flag' => '🇪🇸'],
        ['code' => 'LK', 'name' => 'سريلانكا', 'name_en' => 'Sri Lanka', 'dial_code' => '+94', 'flag' => '🇱🇰'],
        ['code' => 'SR', 'name' => 'سورينام', 'name_en' => 'Suriname', 'dial_code' => '+597', 'flag' => '🇸🇷'],
        ['code' => 'SE', 'name' => 'السويد', 'name_en' => 'Sweden', 'dial_code' => '+46', 'flag' => '🇸🇪'],
        ['code' => 'CH', 'name' => 'سويسرا', 'name_en' => 'Switzerland', 'dial_code' => '+41', 'flag' => '🇨🇭'],
        ['code' => 'TW', 'name' => 'تايوان', 'name_en' => 'Taiwan', 'dial_code' => '+886', 'flag' => '🇹🇼'],
        ['code' => 'TJ', 'name' => 'طاجيكستان', 'name_en' => 'Tajikistan', 'dial_code' => '+992', 'flag' => '🇹🇯'],
        ['code' => 'TZ', 'name' => 'تنزانيا', 'name_en' => 'Tanzania', 'dial_code' => '+255', 'flag' => '🇹🇿'],
        ['code' => 'TH', 'name' => 'تايلاند', 'name_en' => 'Thailand', 'dial_code' => '+66', 'flag' => '🇹🇭'],
        ['code' => 'TL', 'name' => 'تيمور الشرقية', 'name_en' => 'Timor-Leste', 'dial_code' => '+670', 'flag' => '🇹🇱'],
        ['code' => 'TG', 'name' => 'توغو', 'name_en' => 'Togo', 'dial_code' => '+228', 'flag' => '🇹🇬'],
        ['code' => 'TO', 'name' => 'تونغا', 'name_en' => 'Tonga', 'dial_code' => '+676', 'flag' => '🇹🇴'],
        ['code' => 'TT', 'name' => 'ترينيداد وتوباغو', 'name_en' => 'Trinidad & Tobago', 'dial_code' => '+1868', 'flag' => '🇹🇹'],
        ['code' => 'TR', 'name' => 'تركيا', 'name_en' => 'Turkey', 'dial_code' => '+90', 'flag' => '🇹🇷'],
        ['code' => 'TM', 'name' => 'تركمانستان', 'name_en' => 'Turkmenistan', 'dial_code' => '+993', 'flag' => '🇹🇲'],
        ['code' => 'TV', 'name' => 'توفالو', 'name_en' => 'Tuvalu', 'dial_code' => '+688', 'flag' => '🇹🇻'],
        ['code' => 'UG', 'name' => 'أوغندا', 'name_en' => 'Uganda', 'dial_code' => '+256', 'flag' => '🇺🇬'],
        ['code' => 'UA', 'name' => 'أوكرانيا', 'name_en' => 'Ukraine', 'dial_code' => '+380', 'flag' => '🇺🇦'],
        ['code' => 'GB', 'name' => 'المملكة المتحدة', 'name_en' => 'United Kingdom', 'dial_code' => '+44', 'flag' => '🇬🇧'],
        ['code' => 'US', 'name' => 'الولايات المتحدة', 'name_en' => 'United States', 'dial_code' => '+1', 'flag' => '🇺🇸'],
        ['code' => 'UY', 'name' => 'أوروغواي', 'name_en' => 'Uruguay', 'dial_code' => '+598', 'flag' => '🇺🇾'],
        ['code' => 'UZ', 'name' => 'أوزبكستان', 'name_en' => 'Uzbekistan', 'dial_code' => '+998', 'flag' => '🇺🇿'],
        ['code' => 'VU', 'name' => 'فانواتو', 'name_en' => 'Vanuatu', 'dial_code' => '+678', 'flag' => '🇻🇺'],
        ['code' => 'VA', 'name' => 'الفاتيكان', 'name_en' => 'Vatican City', 'dial_code' => '+379', 'flag' => '🇻🇦'],
        ['code' => 'VE', 'name' => 'فنزويلا', 'name_en' => 'Venezuela', 'dial_code' => '+58', 'flag' => '🇻🇪'],
        ['code' => 'VN', 'name' => 'فيتنام', 'name_en' => 'Vietnam', 'dial_code' => '+84', 'flag' => '🇻🇳'],
        ['code' => 'ZM', 'name' => 'زامبيا', 'name_en' => 'Zambia', 'dial_code' => '+260', 'flag' => '🇿🇲'],
        ['code' => 'ZW', 'name' => 'زيمبابوي', 'name_en' => 'Zimbabwe', 'dial_code' => '+263', 'flag' => '🇿🇼'],
    ];
}

/**
 * Get dial code by country ISO code
 */
function hoktech_get_dial_code_by_country($country_code) {
    $countries = hoktech_get_country_codes();
    foreach ($countries as $country) {
        if ($country['code'] === strtoupper($country_code)) {
            return $country['dial_code'];
        }
    }
    return '+20'; // Default to Egypt
}

/**
 * Map WooCommerce country code to dial code (for countries that map to PS instead of IL)
 */
function hoktech_wc_country_to_dial($wc_country) {
    // Map IL to PS (Palestine)
    if ($wc_country === 'IL') {
        $wc_country = 'PS';
    }
    return hoktech_get_dial_code_by_country($wc_country);
}
